configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-226b4e84cf610961f1506b4cad49ce015bbab3463d629a187cc4a6e96ffcb5bd.yml
openapi_spec_hash: 8c6f8bcfec5dfae3cab38fee3763a003
config_hash: 1472d68ac80aaa3be855b4556f0fd646
