configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc/roark-analytics-cc236bee5bdd83775c6aab600849cd9f6c5463778f0da7234d5fbff809ffded2.yml
openapi_spec_hash: 9be8648baeae24ee78a4594e64048eb9
config_hash: 551b3bbc378718df2f83ff06ada88ea4
