configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c31cf1bf167b5285ec6f6ef4ccb1c07e77a868d47fcd321b39ea4e0c7b16cf26.yml
openapi_spec_hash: 1b470d4c0016dfbea2fb36a0da2771c2
config_hash: 5da79209303ea0ffabc86b4e0c2a60b0
