configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-8355ddeb8c8a6cb8f35ad8ffb24f6dfb152378a866336fac09f8f63db6c6cc84.yml
openapi_spec_hash: 9b0ebcdf1a0b9f7aac10d632cca2fda8
config_hash: 1472d68ac80aaa3be855b4556f0fd646
