configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-94a1bfc7214458f9ab5da4a48fcade0aa584619b0b30bbb5b402b56bd0c963af.yml
openapi_spec_hash: 8340b93e1bfb9d465837b4599b9d19af
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
