configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a071f2861be5f8c3942108b8c9aae925d71c16433381aaaaa5acce315a7792b8.yml
openapi_spec_hash: b4abe03df515b04bbf49ea690b7a6ad5
config_hash: 8a241f58fee80d86686c8b50db6ac3ef
