configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d2e1c4ceda14310a9bfc85dbac924819157a575561ec151f563f6aacf4bbddd0.yml
openapi_spec_hash: fdd230e2425cc19fd017b9e90aaf2ff2
config_hash: 728611a22f689f34d824bde7a129e4da
