configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-17146fbd6adcc6f5ac52b77b4db2fd9cc1239fc14ac5b868c65463d09fc1904f.yml
openapi_spec_hash: caf1470f443de053273bb8798bcdf6f3
config_hash: 32ff244fd995bca76457f2e7d0ed502b
