configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-24ae549c0d98cca5d60937824512e2611e1042dbaa8bb5f4e8b4abb605fa64b1.yml
