configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-debcecf225f9cc405ef413374dfc1dccf4ca21d3fc72064c5ad429ddc4b47227.yml
openapi_spec_hash: 72e517f5180439ae36de56adddf18cec
config_hash: 19115bda688fa63841952001e02a0bdf
