configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-3c2c986b88cdab9cdd90c1ceb8baff61c0c5a215c0bbf10dac42907b06bbf0b3.yml
openapi_spec_hash: da235b51fce0f71d4833e2d67b64ceba
config_hash: 0e89994bbc002d06864f15f4146a8756
