configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a22d48c0148b3867db941ef71bf5aa4ed581808011d29df3e5da3bfa132aa97c.yml
openapi_spec_hash: d534ac8a110c632ed8fc1f4d80ce5d26
config_hash: 5da79209303ea0ffabc86b4e0c2a60b0
