configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-2e8b5df7ff90bf27eaa8634c4c97a20f7bcd67a3bab174fa17518dc862b4671c.yml
openapi_spec_hash: fd9ad8ca89aaa4dbbc758167d2ea7084
config_hash: 83c6707500fc13c5609151f9f8c0bc2f
