configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c7488f09782ec7e54dd18e88afc15ae481407a0504e92aacab3f6cac64ac7049.yml
