configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a0e3a118e76bd6fbc348a2d3ae92ea64fff1dd34ac95f4e70a80cf014ec4b74a.yml
openapi_spec_hash: 73e17aeb3a9b811eeaf160e0b73df362
config_hash: 8a241f58fee80d86686c8b50db6ac3ef
