configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c244bbf9ea54f31a23a601af51d90e9fffbf9371ab8a2cd4e29f9887f2d14330.yml
