configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-4be239c6d97170aa80e0ce4dfd6b112c4fa4ed4ab68cfea3c6d68cb01086a088.yml
openapi_spec_hash: 28b90ba4ae4e0b2468ef37a0dae83d4f
config_hash: 2fb733ab721f01f6833d95ec790d43a1
