configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-34a9edea88f76ff789538589145d55efacb02845f912d1ca7ed1a8cfe3dedf80.yml
openapi_spec_hash: af3ed0b0a68a17fc3dbc3223b635ab3c
config_hash: 19115bda688fa63841952001e02a0bdf
