configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-b70f7ac5dc87ac67a9aac49b48abb6500e19a3b03ff8cbcebe6eb8be3edf9de2.yml
openapi_spec_hash: 8103d524f0f50d4c838eb9e866fecf23
config_hash: 3f316fb4194431e01f9ec1570e10eba1
