configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-3b5cef80fbbe0a8c1aa857cdc5df53752d8da8260bdce789b5f9c941546bc1df.yml
openapi_spec_hash: c3d0d50abf1ca34eb61160b4ca4270bc
config_hash: 5d9f3f3561984eb519843565df10a80d
