configured_endpoints: 62
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc/roark-analytics-e93ead0e222fd74d2bafc27d63213c327e555ae3800dbdac1b16a0fa3b3e3900.yml
openapi_spec_hash: c5cfe9cfa58423df71ae2fdb0d4a7321
config_hash: 4f469568a2ea7d6b21803a666cb21b9b
