configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-ec71663e9d7a50449db021a1c566474983cb5d12201ce2ceb2c5cd220c6a38f8.yml
