configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a6feabb69a3c4be9022f1331f379a15f6197ebdb751a1be9eacce88efd8cead1.yml
openapi_spec_hash: a7a7e843f3ff347bde655520fafbabc4
config_hash: 0e89994bbc002d06864f15f4146a8756
