configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a391f11ccef4bf258131e13c14faf5f6efddefcd6770646017353d2eaeecbc5c.yml
openapi_spec_hash: dae769a02c2d50bb4178873aea57231f
config_hash: 3f316fb4194431e01f9ec1570e10eba1
