configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c98c4416bf16e2443e0c8429c0c69182012056355a32c38617991af914c1b0c1.yml
