configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a442dedf6b626b5c8a7e833edeba54afd74b944cf24a7a4adf189e8eaf33c8e0.yml
openapi_spec_hash: bf7e4f5fac0848b0015527601a9ebeee
config_hash: 19115bda688fa63841952001e02a0bdf
