configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-0ff87faeda901b909f8b1a3dadf6711ce0c3c1b43b748a254ba5674e8f3307cd.yml
openapi_spec_hash: f98c29bdfdec2ac4a0edef4fce2de938
config_hash: 8f3316e385354aa7948665acf82c3974
