configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-9a7ded1c676e33b308c7db0e9325ca1c46dafb071e053ca9b3da80a8ca55ea3f.yml
openapi_spec_hash: b10b03e9d514e6c0bb5fceef2d26e567
config_hash: 3f316fb4194431e01f9ec1570e10eba1
