configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-0e522dcb1ef7bf5e54236cdf45256dbcbc5df3f992bda6952cbbc36f98c76486.yml
openapi_spec_hash: 06816517cb8576161b8aee1bf3a54b84
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
