configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-b7fd0dcf37dd0e4cdee9f88ff743f094b3a49539ed8c4db479ccdf0f699b70cb.yml
openapi_spec_hash: c758da8de44eac95df3f3b26a5fefdf2
config_hash: 8f3316e385354aa7948665acf82c3974
