configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d8e3a12c6bb99e2962d378d8dadcb5eda4e6b569b47c95eff67ad64b68dc84b9.yml
openapi_spec_hash: 383f330f3b76d9cbf3ffc94fbfbf6cd8
config_hash: 5d9f3f3561984eb519843565df10a80d
