configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-9d050dc3e4bd02afc7d4dcbaddff4c000949b6dd48b41f71b51b8f84d78a4b89.yml
openapi_spec_hash: bed64f3b8c07126ba2cf58eeccf0dabf
config_hash: 8a241f58fee80d86686c8b50db6ac3ef
