configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-94d88387d658c70c872d2c8d3055c07a2e82b7e55c34bed04f26ca50749efbb0.yml
