configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-ae38fce0a73148bab116cbb2e5bb68a7ef8f6fd122d92f9899e017cbb4384e04.yml
openapi_spec_hash: 150bf8ac2b07c7779421c2392f4a4e5a
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
