configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c3a94282dd3cb57a2ff5e67cde10192de210d38b4c1c9360fbe31145fc53752e.yml
openapi_spec_hash: be54a88d7bc095d6f2144f5ab25fe9f4
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
