configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-5c63179ab428d6817cf1f6dba97ee502e6e479b2fb5937255a431c767f85de9e.yml
openapi_spec_hash: b1850bfbfcdbe4e2211e5ddf2b6f87be
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
