configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d3900dbfacf89caf7ca417aea578c4fc85f54d3ee427f75946275d9df8def83e.yml
openapi_spec_hash: f6976f4a4f13eba2b17a5ba2218c69be
config_hash: 2fb733ab721f01f6833d95ec790d43a1
