configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-41d1a22e1ffc431c3f4fce6c8577095b3b13eb663bbb3f649ed3b7c4d6cb831a.yml
openapi_spec_hash: ddc33b5bceccaef81e51f56f560ebbd0
config_hash: 8f3316e385354aa7948665acf82c3974
