configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-3af9c62ef9bd901d6eda21f81da4c976d1cdbdfc73e0c80a0deed48d970cf708.yml
openapi_spec_hash: 28ae958c52ad3eac34eff983701b1e25
config_hash: 19115bda688fa63841952001e02a0bdf
