configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-eb81bbc80aa0e04fea61ba4bcc211a100c4df9acd17ae5aa3a0a222bbe2c8ad6.yml
openapi_spec_hash: b2d31f8ecac4935b021dca5659d405c5
config_hash: 8f3316e385354aa7948665acf82c3974
