configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-78e49c15be59d76e9bf82e9296737674d4cdaa786e8d1ca34472cdea754ac1d3.yml
