configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-243fabadce701f3057ab4caff9f1acc47dbfabf2f53bc705d25a0db06efe25aa.yml
openapi_spec_hash: 4f826eed0a693937e8b361fa3e4655c0
config_hash: 8f3316e385354aa7948665acf82c3974
