configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-922f60559f3432310a4e973431cd86c6a3bce6bc7bb0e1bb49a1ceaa1aab59be.yml
openapi_spec_hash: 4cfefb96cd8bdb4bb4f513d2e6bdaf37
config_hash: 8f3316e385354aa7948665acf82c3974
