configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-9fd9cd3c6e2215bdfca7f2bf3f3193bdb04175df7b2b71d238d4dd719c503d48.yml
openapi_spec_hash: 99e5beb4460affcc6dc565b95db3a9a4
config_hash: 2fb733ab721f01f6833d95ec790d43a1
