configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d342a3441a0af4e775ce3bff8c2172f3cbf5bf36680ff65ab7e4ef0eb6840cdd.yml
openapi_spec_hash: de1adcf26385f5c098b3147386a69c4b
config_hash: 1472d68ac80aaa3be855b4556f0fd646
