configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-5b9ae3b3ab700c5b50f9fadbcb8e991aaa1d995e1e0d6b8399bbc062a7ed48e7.yml
openapi_spec_hash: 0c15fac1da145f119968ceaf46051cd6
config_hash: 1472d68ac80aaa3be855b4556f0fd646
