configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-0aeb8523faced623573f163d4f6fcfa0fdf000501a5558c15a8eb9e7931d757e.yml
openapi_spec_hash: 6f6ab0bba4e609f7946eb6d50f3b72fc
config_hash: 8a241f58fee80d86686c8b50db6ac3ef
