configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-6b0731087e66d07ace62bcca3ab90a87e761ef8cbdf1566a09c2bbfa36987088.yml
openapi_spec_hash: a4fe274fffd88ebca2f6a1b8f1136367
config_hash: 8b826333eccec69eb9eab24b3c40c0e9
