configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-f6df0acea4898a04ca3336db25ccd93faebb041f82a8ced938fd403d99cd9393.yml
openapi_spec_hash: b82e9d7d357a618feeb8c183ca42b85e
config_hash: 32ff244fd995bca76457f2e7d0ed502b
