configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-6fd6fe5421ffd8dbcba936a2e85301f4bd61907e59db5c16fcbb1f27aeef2a54.yml
openapi_spec_hash: 4b51488aac180897ee51f971ac13fc8b
config_hash: 1472d68ac80aaa3be855b4556f0fd646
