configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-3a4a58a9fcef303d6d9f7d08a3f82cebedba782f9ece0cca1028b8d85815d06e.yml
openapi_spec_hash: ceda7857057d978fc93120dceb4d50aa
config_hash: ca3d50118e1c012fcd322ada5ff4a11c
