# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = ["CallGetByIDResponse", "Data", "DataAgent", "DataAgentEndpoint", "DataCustomer"]


class DataAgentEndpoint(BaseModel):
    id: str

    environment: str

    phone_number_e164: Optional[str] = FieldInfo(alias="phoneNumberE164", default=None)


class DataAgent(BaseModel):
    id: str

    endpoint: DataAgentEndpoint


class DataCustomer(BaseModel):
    phone_number_e164: Optional[str] = FieldInfo(alias="phoneNumberE164", default=None)


class Data(BaseModel):
    id: str
    """Unique identifier for the call"""

    call_direction: Literal["INBOUND", "OUTBOUND"] = FieldInfo(alias="callDirection")
    """Direction of the call (inbound or outbound)"""

    project_id: str = FieldInfo(alias="projectId")
    """ID of the project this call belongs to"""

    started_at: str = FieldInfo(alias="startedAt")
    """Timestamp when the call started"""

    agents: Optional[List[DataAgent]] = None
    """Agent information"""

    created_at: Optional[str] = FieldInfo(alias="createdAt", default=None)
    """Timestamp when the call record was created"""

    customers: Optional[List[DataCustomer]] = None
    """Customer information"""

    duration_ms: Optional[float] = FieldInfo(alias="durationMs", default=None)
    """Duration of the call in milliseconds"""

    ended_at: Optional[str] = FieldInfo(alias="endedAt", default=None)
    """Timestamp when the call ended"""

    ended_status: Optional[
        Literal[
            "PARTICIPANTS_DID_NOT_SPEAK",
            "AGENT_DID_NOT_ANSWER",
            "AGENT_DID_NOT_SPEAK",
            "AGENT_STOPPED_SPEAKING",
            "AGENT_ENDED_CALL",
            "AGENT_TRANSFERRED_CALL",
            "AGENT_BUSY",
            "AGENT_ERROR",
            "CUSTOMER_ENDED_CALL",
            "VOICE_MAIL_REACHED",
            "SILENCE_TIME_OUT",
            "PHONE_CALL_PROVIDER_CONNECTION_ERROR",
            "CUSTOMER_DID_NOT_ANSWER",
            "CUSTOMER_DID_NOT_SPEAK",
            "CUSTOMER_STOPPED_SPEAKING",
            "CUSTOMER_BUSY",
            "DIAL_ERROR",
            "MAX_DURATION_REACHED",
            "UNKNOWN",
        ]
    ] = FieldInfo(alias="endedStatus", default=None)
    """Status indicating how the call ended"""

    recording_url: Optional[str] = FieldInfo(alias="recordingUrl", default=None)
    """Pre-signed URL to the call recording (expires in 1 hour)"""

    simulation_job_id: Optional[str] = FieldInfo(alias="simulationJobId", default=None)
    """ID of the simulation job if this call was generated by a simulation"""

    status: Optional[Literal["RINGING", "IN_PROGRESS", "ENDED"]] = None
    """Current status of the call"""

    summary: Optional[str] = None
    """Auto-generated summary of the call conversation"""

    superseded_by_call_id: Optional[str] = FieldInfo(alias="supersededByCallId", default=None)
    """ID of the call that superseded this one (if applicable)"""

    title: Optional[str] = None
    """Auto-generated title for the call based on content"""

    updated_at: Optional[str] = FieldInfo(alias="updatedAt", default=None)
    """Timestamp when the call record was last updated"""


class CallGetByIDResponse(BaseModel):
    data: Data
    """Response containing call information"""
