# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Optional
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = [
    "SimulationCustomerFlowGetByIDResponse",
    "Data",
    "DataAgentExpectation",
    "DataVariant",
    "DataVariantAdditionalExpectation",
]


class DataAgentExpectation(BaseModel):
    """An expectation the agent under test is graded against.

    On a scripted flow these are derived from the agent turns in the graph, so they are read-only there.
    """

    id: str

    llm_prompt: str = FieldInfo(alias="llmPrompt")

    order_index: int = FieldInfo(alias="orderIndex")

    source_step_node_id: Optional[str] = FieldInfo(alias="sourceStepNodeId", default=None)


class DataVariantAdditionalExpectation(BaseModel):
    """An expectation the agent under test is graded against.

    On a scripted flow these are derived from the agent turns in the graph, so they are read-only there.
    """

    id: str

    llm_prompt: str = FieldInfo(alias="llmPrompt")

    order_index: int = FieldInfo(alias="orderIndex")

    source_step_node_id: Optional[str] = FieldInfo(alias="sourceStepNodeId", default=None)


class DataVariant(BaseModel):
    """One way of running a flow.

    Exactly one variant per flow is the default; the others inherit its persona and environment wherever they leave those unset. On a scripted flow each variant is bound to one path through the graph and the path engine owns that binding.
    """

    id: str

    additional_expectations: List[DataVariantAdditionalExpectation] = FieldInfo(alias="additionalExpectations")

    created_at: str = FieldInfo(alias="createdAt")
    """Creation timestamp in ISO 8601 format"""

    customer_flow_id: str = FieldInfo(alias="customerFlowId")

    environment_id: Optional[str] = FieldInfo(alias="environmentId", default=None)

    is_auto_generated_title: bool = FieldInfo(alias="isAutoGeneratedTitle")

    is_default: bool = FieldInfo(alias="isDefault")

    is_generated: bool = FieldInfo(alias="isGenerated")

    latest_path_id: Optional[str] = FieldInfo(alias="latestPathId", default=None)

    persona_id: Optional[str] = FieldInfo(alias="personaId", default=None)

    preceded_by_customer_flow_id: Optional[str] = FieldInfo(alias="precededByCustomerFlowId", default=None)

    preceded_by_customer_flow_variant_id: Optional[str] = FieldInfo(
        alias="precededByCustomerFlowVariantId", default=None
    )

    title: str

    updated_at: str = FieldInfo(alias="updatedAt")
    """Last update timestamp in ISO 8601 format"""

    prompt: Optional[str] = None


class Data(BaseModel):
    """
    A customer flow: the conversation a simulated customer has with the agent under test. Flows with source SYSTEM are curated by Roark, shared across projects, and read-only.
    """

    id: str

    agent_expectations: List[DataAgentExpectation] = FieldInfo(alias="agentExpectations")

    agent_ids: List[str] = FieldInfo(alias="agentIds")
    """Agents this flow exercises"""

    created_at: str = FieldInfo(alias="createdAt")
    """Creation timestamp in ISO 8601 format"""

    mode: Literal["UNSCRIPTED", "SCRIPTED", "VOICEMAIL"]

    scripted_branching_mode: Literal["DETERMINISTIC", "ADAPTIVE"] = FieldInfo(alias="scriptedBranchingMode")

    source: Literal["SYSTEM", "CUSTOM"]

    start_node_id: Optional[str] = FieldInfo(alias="startNodeId", default=None)

    title: str

    updated_at: str = FieldInfo(alias="updatedAt")
    """Last update timestamp in ISO 8601 format"""

    variants: List[DataVariant]

    description: Optional[str] = None

    steps: Optional[List["FlowStep"]] = None
    """The conversation, as a tree of steps. Scripted flows only."""

    steps_shared_with_other_flows: Optional[List[str]] = FieldInfo(alias="stepsSharedWithOtherFlows", default=None)
    """Steps that another flow also uses.

    Removing one of these detaches it from this flow rather than deleting it, so the
    other flow keeps working.
    """

    system_key: Optional[str] = FieldInfo(alias="systemKey", default=None)


class SimulationCustomerFlowGetByIDResponse(BaseModel):
    data: Data
    """
    A customer flow: the conversation a simulated customer has with the agent under
    test. Flows with source SYSTEM are curated by Roark, shared across projects, and
    read-only.
    """


from .flow_step import FlowStep
