# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Optional

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = ["SimulationCustomerFlowReplaceStepsResponse", "Data", "DataVariant", "DataVariantAdditionalExpectation"]


class DataVariantAdditionalExpectation(BaseModel):
    """An expectation the agent under test is graded against.

    On a scripted flow these are derived from the agent turns in the graph, so they are read-only there.
    """

    id: str

    llm_prompt: str = FieldInfo(alias="llmPrompt")

    order_index: int = FieldInfo(alias="orderIndex")

    source_step_node_id: Optional[str] = FieldInfo(alias="sourceStepNodeId", default=None)


class DataVariant(BaseModel):
    """One way of running a flow.

    Exactly one variant per flow is the default; the others inherit its persona and environment wherever they leave those unset. On a scripted flow each variant is bound to one path through the graph and the path engine owns that binding.
    """

    id: str

    additional_expectations: List[DataVariantAdditionalExpectation] = FieldInfo(alias="additionalExpectations")

    created_at: str = FieldInfo(alias="createdAt")
    """Creation timestamp in ISO 8601 format"""

    customer_flow_id: str = FieldInfo(alias="customerFlowId")

    environment_id: Optional[str] = FieldInfo(alias="environmentId", default=None)

    is_auto_generated_title: bool = FieldInfo(alias="isAutoGeneratedTitle")

    is_default: bool = FieldInfo(alias="isDefault")

    is_generated: bool = FieldInfo(alias="isGenerated")

    latest_path_id: Optional[str] = FieldInfo(alias="latestPathId", default=None)

    persona_id: Optional[str] = FieldInfo(alias="personaId", default=None)

    preceded_by_customer_flow_id: Optional[str] = FieldInfo(alias="precededByCustomerFlowId", default=None)

    preceded_by_customer_flow_variant_id: Optional[str] = FieldInfo(
        alias="precededByCustomerFlowVariantId", default=None
    )

    title: str

    updated_at: str = FieldInfo(alias="updatedAt")
    """Last update timestamp in ISO 8601 format"""

    prompt: Optional[str] = None


class Data(BaseModel):
    steps: List["FlowStep"]

    steps_shared_with_other_flows: List[str] = FieldInfo(alias="stepsSharedWithOtherFlows")

    variants: List[DataVariant]
    """The variants after the write."""

    variants_reshaped: bool = FieldInfo(alias="variantsReshaped")
    """
    True when the write changed the set of paths, so the flow's variants were
    re-seeded and any variant id you were holding may no longer exist.
    """

    warnings: List[str]


class SimulationCustomerFlowReplaceStepsResponse(BaseModel):
    data: Data


from .flow_step import FlowStep
